language: java
jdk:
  - oraclejdk8
env:
  - TERM=dumb
before_install:
  - sudo apt-get update
  - sudo apt-get install --only-upgrade -y oracle-java8-installer
install:
  - /bin/true
script:
  - ./gradlew -PBINTRAY_USER -PBINTRAY_API_KEY build
